args:
  _examples: |
    main.py -r proxy --build -bf

  basepath:
    _type: str

  deploy_path:
    _type: dir

  profile:
    _aliases: --profile,-r
    _default: debug
    _required: true
    _type: str
    default:
      _info: set default url if exists to hostname_url when selected

  backend:
    _aliases: --backend,-b
    _need_child: true
    _xor: build,deploy,start,publish
    settings:
      csproj:
        _type: file

      msbuild:
        _info: msbuild path
        _type: file

      msdeploy:
        _info: msdeploy path
        _type: file

      sources:
        _type: dir

    build: 
      _aliases: --build,-b
      _info: build project.

    deploy:
      _aliases: --deploy,-d
      _info: default DEPLOY_PATH is {USERPROFILE}/{GLOBAL_SETTINGS:PROXY_PATH}{USER_SETTINGS:BASEPATH}/
      _label: DEPLOY_PATH
      _type: dir
      _values: "?"
      "@":  args.substitute
      force:
        _info: force building even if project is up-to-date

    dotnet:
      _aliases: --dotnet,-t
      _info: cd sources directory and dotnet command with arguments
      _values: "+"
      _label: ARG

    start:
      _aliases: --start,-s
      _info: build project and start development server.

    publish: 
      _aliases: --publish,-p
      _info: PUBLISH_PATH is {PWD}/src/_publish
      force:
        _info: force building even if project is up-to-date

  frontend:
    _aliases: --frontend,-f
    _need_child: true
    _xor: build,deploy,npm,start,publish
    settings:
      minify:
        _type: bool
      npm:
        _info: npm path
        _type: str
      webroot:
        _info: set web root path
      sources:
        _type: dir

    build:
      _aliases: --build,-b
      _info: build project.

    deploy:
      _aliases: --deploy,-d
      _info: default DEPLOY_PATH is {USERPROFILE}/{GLOBAL_SETTINGS:PROXY_PATH}{USER_SETTINGS:BASEPATH}/{USER_SETTINGS:WEBROOT}
      _label: DEPLOY_PATH
      _type: dir
      _values: "?"

    npm:
      _aliases: --npm,-n
      _info: cd sources directory and npm command with arguments
      _values: "+"
      _label: ARG

    publish:
      _aliases: --publish,-p
      _info: PUBLISH_PATH is {PWD}/src/_publish/{USER_SETTINGS:WEBROOT}

    start:
      _aliases: --start,-s
      _info: build project and start development server.
      ignore_if:
        _aliases: --ignore-if,-i
        _info: if server is already started then command is ignored
      port:
        _info: development server port
        _type: int

  project:
    _info: provide project name
    _type: str

  not_git:
    _info: if this option is not selected and the folder is a git project, then os.getcwd() is changed to git root directory

  substitute:
    _info: substitute variables placeholders with values, If --vars are provided then vars in .wapp.json are ignored if any. If --dst are provided then dst files in .wapp.json are ignored if any.
    vars:
      _info: files that contain variables, variable files are merged into one dictionary
      _type: .json
      _values: +
    dst:
      _info: files that contain variables placeholders that need to be substituted. variables placeholders must be of form {{[a-zA-Z0-9-_]+}} i.e. {{SPLUNK-TOKEN}}
      _type: vpath
      _values: +





